backend:
  name: github
  repo: AndyNortrup/AndyNortrup.github.io
  branch: main # Branch to update (optional; defaults to master)

local_backend: true

media_folder: "static/images/uploads" #media files will be stored in the repo under images/uploads
public_folder: "/images/uploads"

display_url: "https://www.nortrup.dev"

collections:
  - name: product
    identifier_field: name
    extension: "md"
    folder: 'content/posts/product-management'
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    label: 'Product Management'
    create: true
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", default: ["ProductManagement"]}
  - name: productops
    identifier_field: name
    extension: "md"
    folder: 'content/posts/productoperations'
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    label: 'Product Opreations'
    create: true
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", default: ["ProductOps"]}
      - {label: "Category", name: "category", widget: "string", default: "Product Operations"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: star_magnolia
    identifier_field: name
    extension: "md"
    folder: 'content/posts/bonsai/star-magnolia'
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    label: 'Bonsai / Star Magnolia'
    create: true
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list", default: ["bonsai"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
 